path = 'images\\'
path_elements = path+'elements\\'
path_menu = path+'menu\\'
width = 640
height = 480
take = False
escape_press = False
screen_width = None # изменится на разререшение экрана
screen_height = None # изменится на разререшение экрана
canvas = None # изменится на canvas
last_tag_of_overlap = ''
font_multiplier = 5
mini = min(height, width)
coords_xy = [int(mini//2.3)//2, mini//16]
options_width=mini//2.23
options_height=mini//2.56
element_counter = 4
all_elements = '???' # Изменится на количество элементов
resize = False
this_style = True
